In [5]:
#import libraries
#!pip install kaggle
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [7]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [22]:
import pandas as pd
df = pd.read_csv('orders.csv')
df.head(25)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3
20,21,2022-10-05,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Binders,OFF-BI-10002215,20,20,4,2
21,22,2023-07-16,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Art,OFF-AR-10000246,20,20,7,4
22,23,2023-05-06,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Appliances,OFF-AP-10001492,50,60,7,3
23,24,2023-05-21,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Chairs,FUR-CH-10002774,60,70,2,4
24,25,2023-02-24,Standard Class,Consumer,United States,Orem,Utah,84057,West,Furniture,Tables,FUR-TA-10000577,900,1040,3,5

In [38]:
#df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
#df['Ship Mode'].unique()
#df.columns = df.columns.str.lower()
#df.columns = df.columns.str.replace(' ','_')

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,52.0
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,219.0
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,5.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,192.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,10.0

In [41]:
df['discount']=df['list_price']*df['discount_percent']/100
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0

In [47]:
#df['sale_price']= df['list_price']-df['discount']
df['profit']= df['sale_price']-df['cost_price']
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [49]:
#df.dtypes
pd.to_datetime(df['order_date'],format="%Y-%m-%d")

0      2023-03-01
1      2023-08-15
2      2023-01-10
3      2022-06-18
4      2022-07-13
          ...
9989   2023-02-18
9990   2023-03-17
9991   2022-08-07
9992   2022-11-19
9993   2022-07-17
Name: order_date, Length: 9994, dtype: datetime64[ns]

In [57]:
#df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [59]:
import sqlalchemy as sql
from sqlalchemy import create_engine
import pandas as pd
!pip install psycopg2

# Replace 'your_username', 'your_password', 'your_host', 'your_port', and 'your_database' with your PostgreSQL credentials
engine = create_engine('postgresql+psycopg2://postgres:1234@localhost:5432/SQL_PYTHON_PROJECT')
conn = engine.connect()

Collecting psycopg2
  Downloading psycopg2-2.9.9-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
Downloading psycopg2-2.9.9-cp311-cp311-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB 660.6 kB/s eta 0:00:02
   -- ------------------------------------- 0.1/1.2 MB 787.7 kB/s eta 0:00:02
   ---- ----------------------------------- 0.1/1.2 MB 901.1 kB/s eta 0:00:02
   ---- ----------------------------------- 0.1/1.2 MB 853.3 kB/s eta 0:00:02
   ------ --------------------------------- 0.2/1.2 MB 787.7 kB/s eta 0:00:02
   ------- -------------------------------- 0.2/1.2 MB 657.3 kB/s eta 0:00:02
   ------- -------------------------------- 0.2/1.2 MB 655.6 kB/s eta 0:00:02
   -------- ------------------------------- 0.2/1.2 MB 600.7 kB/s eta 0:00:02
   -------- ------------------------------- 0.2/1.2 MB 600.7 kB/s eta 0:00:02
   -------- ------------------------------- 0.3/1.2 MB 525.1 kB/s eta 0:00:02
   -------- ------------------------------- 0.3/1.2 MB 525.1 kB/s eta 0:00:02
   --------- ------------------------------ 0.3/1.2 MB 460.6 kB/s eta 0:00:02
   --------- ------------------------------ 0.3/1.2 MB 460.6 kB/s eta 0:00:02
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   --------- ------------------------------ 0.3/1.2 MB 421.5 kB/s eta 0:00:03
   ------------ --------------------------- 0.4/1.2 MB 200.8 kB/s eta 0:00:05
   ------------ --------------------------- 0.4/1.2 MB 200.8 kB/s eta 0:00:05
   ------------ --------------------------- 0.4/1.2 MB 196.1 kB/s eta 0:00:05
   ------------ --------------------------- 0.4/1.2 MB 196.1 kB/s eta 0:00:05
   ------------- -------------------------- 0.4/1.2 MB 197.2 kB/s eta 0:00:04
   ------------- -------------------------- 0.4/1.2 MB 199.2 kB/s eta 0:00:04
   --------------- ------------------------ 0.4/1.2 MB 211.8 kB/s eta 0:00:04
   --------------- ------------------------ 0.4/1.2 MB 211.8 kB/s eta 0:00:04
   ---------------- ----------------------- 0.5/1.2 MB 225.1 kB/s eta 0:00:04
   ----------------- ---------------------- 0.5/1.2 MB 226.4 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ----------------- ---------------------- 0.5/1.2 MB 234.1 kB/s eta 0:00:03
   ------------------ --------------------- 0.5/1.2 MB 168.8 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 200.9 kB/s eta 0:00:03
   --------------------- ------------------ 0.6/1.2 MB 200.9 kB/s eta 0:00:03
   --------------------- ------------------ 0.6/1.2 MB 200.9 kB/s eta 0:00:03
   --------------------- ------------------ 0.6/1.2 MB 200.9 kB/s eta 0:00:03
   --------------------- ------------------ 0.6/1.2 MB 200.9 kB/s eta 0:00:03
   ----------------------- ---------------- 0.7/1.2 MB 204.3 kB/s eta 0:00:03
   ------------------------ --------------- 0.7/1.2 MB 208.6 kB/s eta 0:00:03
   ------------------------- -------------- 0.7/1.2 MB 211.6 kB/s eta 0:00:02
   --------------------------- ------------ 0.8/1.2 MB 222.4 kB/s eta 0:00:02
   ----------------------------- ---------- 0.9/1.2 MB 236.5 kB/s eta 0:00:02
   ------------------------------- -------- 0.9/1.2 MB 246.5 kB/s eta 0:00:02
   --------------------------------- ------ 1.0/1.2 MB 257.2 kB/s eta 0:00:01
   ----------------------------------- ---- 1.0/1.2 MB 270.3 kB/s eta 0:00:01
   ------------------------------------ --- 1.1/1.2 MB 275.2 kB/s eta 0:00:01
   -------------------------------------- - 1.1/1.2 MB 285.4 kB/s eta 0:00:01
   ---------------------------------------  1.1/1.2 MB 288.4 kB/s eta 0:00:01
   ---------------------------------------  1.2/1.2 MB 290.1 kB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 289.5 kB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.9

In [69]:
df.to_sql('df_orders', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "df_orders_pkey"
DETAIL:  Key (order_id)=(1) already exists.

[SQL: INSERT INTO df_orders (order_id, order_date, ship_mode, segment, country, city, state, postal_code, region, category, sub_category, product_id, quantity, discount, sale_price, profit) VALUES (%(order_id__0)s, %(order_date__0)s, %(ship_mode__0)s, %(se ... 305079 characters truncated ... )s, %(product_id__999)s, %(quantity__999)s, %(discount__999)s, %(sale_price__999)s, %(profit__999)s)]
[parameters: {'category__0': 'Furniture', 'segment__0': 'Consumer', 'quantity__0': 2, 'discount__0': 5.2, 'sale_price__0': 254.8, 'country__0': 'United States', 'ship_mode__0': 'Second Class', 'region__0': 'South', 'sub_category__0': 'Bookcases', 'state__0': 'Kentucky', 'product_id__0': 'FUR-BO-10001798', 'postal_code__0': 42420, 'order_date__0': '2023-03-01', 'order_id__0': 1, 'profit__0': 14.800000000000011, 'city__0': 'Henderson', 'category__1': 'Furniture', 'segment__1': 'Consumer', 'quantity__1': 3, 'discount__1': 21.9, 'sale_price__1': 708.1, 'country__1': 'United States', 'ship_mode__1': 'Second Class', 'region__1': 'South', 'sub_category__1': 'Chairs', 'state__1': 'Kentucky', 'product_id__1': 'FUR-CH-10000454', 'postal_code__1': 42420, 'order_date__1': '2023-08-15', 'order_id__1': 2, 'profit__1': 108.10000000000002, 'city__1': 'Henderson', 'category__2': 'Office Supplies', 'segment__2': 'Corporate', 'quantity__2': 2, 'discount__2': 0.5, 'sale_price__2': 9.5, 'country__2': 'United States', 'ship_mode__2': 'Second Class', 'region__2': 'West', 'sub_category__2': 'Labels', 'state__2': 'California', 'product_id__2': 'OFF-LA-10000240', 'postal_code__2': 90036, 'order_date__2': '2023-01-10', 'order_id__2': 3, 'profit__2': -0.5, 'city__2': 'Los Angeles', 'category__3': 'Furniture', 'segment__3': 'Consumer' ... 15900 parameters truncated ... 'profit__996': -0.40000000000000036, 'city__996': 'Henderson', 'category__997': 'Office Supplies', 'segment__997': 'Consumer', 'quantity__997': 3, 'discount__997': 1.2, 'sale_price__997': 38.8, 'country__997': 'United States', 'ship_mode__997': 'Standard Class', 'region__997': 'South', 'sub_category__997': 'Storage', 'state__997': 'Kentucky', 'product_id__997': 'OFF-ST-10004258', 'postal_code__997': 42420, 'order_date__997': '2023-02-17', 'order_id__997': 998, 'profit__997': 8.799999999999997, 'city__997': 'Henderson', 'category__998': 'Furniture', 'segment__998': 'Consumer', 'quantity__998': 5, 'discount__998': 0.4, 'sale_price__998': 19.6, 'country__998': 'United States', 'ship_mode__998': 'Standard Class', 'region__998': 'South', 'sub_category__998': 'Furnishings', 'state__998': 'Kentucky', 'product_id__998': 'FUR-FU-10002885', 'postal_code__998': 42420, 'order_date__998': '2023-11-25', 'order_id__998': 999, 'profit__998': -0.3999999999999986, 'city__998': 'Henderson', 'category__999': 'Furniture', 'segment__999': 'Consumer', 'quantity__999': 7, 'discount__999': 0.9, 'sale_price__999': 29.1, 'country__999': 'United States', 'ship_mode__999': 'Standard Class', 'region__999': 'South', 'sub_category__999': 'Furnishings', 'state__999': 'Kentucky', 'product_id__999': 'FUR-FU-10001918', 'postal_code__999': 42420, 'order_date__999': '2023-09-05', 'order_id__999': 1000, 'profit__999': -0.8999999999999986, 'city__999': 'Henderson'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)